# Generated by Django 4.2.7 on 2026-05-08 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='currency',
            field=models.CharField(choices=[('NPR', 'Nepalese Rupee'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('INR', 'Indian Rupee'), ('AUD', 'Australian Dollar'), ('CAD', 'Canadian Dollar'), ('SGD', 'Singapore Dollar'), ('AED', 'UAE Dirham')], default='NPR', max_length=3),
        ),
    ]
