# Generated by Django 4.2.7 on 2026-05-22 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_tenant_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='notification_settings',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
