# Generated by Django 4.2.7 on 2026-05-22 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_tenant_notification_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='payment_settings',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
