# Generated by Django 4.2.7 on 2026-05-08 18:26

import uuid
import django.utils.timezone
from django.db import migrations, models
import django.db.models.deletion


DEFAULT_ROOM_TYPES = [
    ('standard', 'Standard', 1, 2, '80.00'),
    ('deluxe', 'Deluxe', 1, 3, '120.00'),
    ('suite', 'Suite', 2, 4, '220.00'),
]


def create_room_types_and_backfill(apps, schema_editor):
    RoomType = apps.get_model('bookings', 'RoomType')
    Room = apps.get_model('bookings', 'Room')

    default_types = {}
    for code, name, base_occupancy, max_occupancy, base_rate in DEFAULT_ROOM_TYPES:
        room_type, _ = RoomType.objects.get_or_create(
            code=code,
            defaults={
                'name': name,
                'base_occupancy': base_occupancy,
                'max_occupancy': max_occupancy,
                'base_rate': base_rate,
                'is_active': True,
            },
        )
        default_types[code] = room_type

    fallback = default_types['standard']
    for room in Room.objects.all():
        legacy_name = (getattr(room, 'room_type', '') or '').strip()
        if legacy_name:
            code = legacy_name.lower().replace(' ', '_')[:30] or 'standard'
            room_type, _ = RoomType.objects.get_or_create(
                code=code,
                defaults={
                    'name': legacy_name,
                    'base_occupancy': 1,
                    'max_occupancy': max(room.capacity or 1, 1),
                    'base_rate': room.price_per_night or fallback.base_rate,
                    'is_active': True,
                },
            )
        else:
            room_type = fallback
        room.room_type_fk = room_type
        room.save(update_fields=['room_type_fk'])


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('base_occupancy', models.PositiveIntegerField(default=1)),
                ('max_occupancy', models.PositiveIntegerField(default=2)),
                ('base_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('amenities', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='room',
            name='room_type_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='bookings.roomtype'),
        ),
        migrations.RunPython(create_room_types_and_backfill, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='room',
            name='room_type',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='room_type_fk',
            new_name='room_type',
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='bookings.roomtype'),
        ),
    ]
