# Generated by Django 4.2.7 on 2026-05-09 06:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_guestfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestFolioLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('source_module', models.CharField(max_length=80)),
                ('source_id', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('folio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='bookings.guestfolio')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='guestfolioline',
            constraint=models.UniqueConstraint(fields=('source_module', 'source_id'), name='unique_folio_source_charge'),
        ),
    ]
