# Generated by Django 4.2.7 on 2026-05-14 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_guestfolioline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='marketing_opt_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guest',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='preferences',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='guest',
            name='vip_level',
            field=models.CharField(choices=[('standard', 'Standard'), ('vip', 'VIP'), ('blacklist', 'Do Not Book')], default='standard', max_length=20),
        ),
    ]
