# Generated by Django 4.2.7 on 2026-05-16 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0006_loyaltyprogram_package_rateplan_guestpoints_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestCommunication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('in_person', 'In Person'), ('note', 'Internal Note')], max_length=30)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound'), ('internal', 'Internal')], default='internal', max_length=30)),
                ('subject', models.CharField(blank=True, max_length=160)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('logged', 'Logged'), ('sent', 'Sent'), ('failed', 'Failed'), ('follow_up', 'Follow Up')], default='logged', max_length=30)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communications', to='bookings.booking')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guest_communications', to=settings.AUTH_USER_MODEL)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='bookings.guest')),
            ],
            options={
                'ordering': ['-occurred_at', '-created_at'],
                'indexes': [models.Index(fields=['guest', '-occurred_at'], name='bookings_gu_guest_i_eec0c6_idx'), models.Index(fields=['booking', '-occurred_at'], name='bookings_gu_booking_6a3ec6_idx'), models.Index(fields=['status'], name='bookings_gu_status_489e92_idx')],
            },
        ),
    ]
