# Generated by Django 4.2.7 on 2026-05-17 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_restaurantorder_cashier_shift'),
        ('bookings', '0007_guestcommunication'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestfolio',
            name='cashier_shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guest_folios', to='restaurant.cashiershift'),
        ),
    ]
