# Generated by Django 4.2.7 on 2026-05-18 04:11

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_guestfolio_cashier_shift'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('category', models.CharField(choices=[('pool', 'Pool'), ('spa', 'Spa'), ('laundry', 'Laundry'), ('minibar', 'Minibar'), ('extra_bed', 'Extra Bed'), ('transport', 'Transport'), ('banquet', 'Banquet'), ('other', 'Other')], default='other', max_length=30)),
                ('default_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['category', 'name'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='bookings_fa_categor_1b8ec2_idx'), models.Index(fields=['code'], name='bookings_fa_code_30446d_idx')],
            },
        ),
    ]
