# Generated by Django 4.2.7 on 2026-05-18 04:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_facilityservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityAmenity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='facilityservice',
            options={'ordering': ['amenity__name', 'category', 'name']},
        ),
        migrations.AddField(
            model_name='facilityservice',
            name='amenity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='services', to='bookings.facilityamenity'),
        ),
        migrations.AddIndex(
            model_name='facilityservice',
            index=models.Index(fields=['amenity', 'is_active'], name='bookings_fa_amenity_96a6e4_idx'),
        ),
        migrations.AddIndex(
            model_name='facilityamenity',
            index=models.Index(fields=['code'], name='bookings_fa_code_940c87_idx'),
        ),
        migrations.AddIndex(
            model_name='facilityamenity',
            index=models.Index(fields=['is_active'], name='bookings_fa_is_acti_83e241_idx'),
        ),
    ]
