# Generated by Django 4.2.7 on 2026-05-22 06:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0011_backfill_room_charge_folio_lines'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestFollowUpReminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('reminder_type', models.CharField(choices=[('arrival', 'Upcoming Arrival'), ('vip', 'VIP Follow Up'), ('payment', 'Payment Follow Up'), ('post_stay', 'Post-Stay Follow Up'), ('custom', 'Custom')], default='custom', max_length=30)),
                ('status', models.CharField(choices=[('open', 'Open'), ('snoozed', 'Snoozed'), ('completed', 'Completed'), ('canceled', 'Canceled')], db_index=True, default='open', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=20)),
                ('subject', models.CharField(max_length=160)),
                ('message', models.TextField(blank=True)),
                ('due_at', models.DateTimeField(db_index=True)),
                ('snoozed_until', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('follow_up_notes', models.TextField(blank=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_guest_follow_ups', to=settings.AUTH_USER_MODEL)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_up_reminders', to='bookings.booking')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_guest_follow_ups', to=settings.AUTH_USER_MODEL)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_up_reminders', to='bookings.guest')),
            ],
            options={
                'ordering': ['status', 'due_at', '-priority'],
                'indexes': [models.Index(fields=['status', 'due_at'], name='bookings_gu_status_96d57a_idx'), models.Index(fields=['guest', 'status'], name='bookings_gu_guest_i_c900da_idx'), models.Index(fields=['booking', 'status'], name='bookings_gu_booking_a349ff_idx'), models.Index(fields=['reminder_type', 'status'], name='bookings_gu_reminde_ad0aca_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='guestfollowupreminder',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['open', 'snoozed'])), fields=('guest', 'booking', 'reminder_type', 'subject'), name='unique_active_guest_follow_up'),
        ),
    ]
