# Generated by Django 4.2.7 on 2026-05-24 04:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0012_guestfollowupreminder_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicPricingRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=120)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField()),
                ('adjustment_type', models.CharField(choices=[('surcharge', 'Surcharge'), ('discount', 'Discount')], default='surcharge', max_length=20)),
                ('value_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='percentage', max_length=20)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_occupancy', models.PositiveIntegerField(blank=True, null=True)),
                ('max_occupancy', models.PositiveIntegerField(blank=True, null=True)),
                ('days_of_week', models.JSONField(blank=True, default=list)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('rate_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_pricing_rules', to='bookings.rateplan')),
                ('room_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_pricing_rules', to='bookings.roomtype')),
            ],
            options={
                'ordering': ['priority', 'name'],
            },
        ),
    ]
