# Generated by Django 4.2.7 on 2026-05-22 04:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationevent',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationevent',
            name='acknowledged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_notification_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationevent',
            name='follow_up_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='notificationevent',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationevent',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_notification_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationevent',
            name='workflow_status',
            field=models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], db_index=True, default='open', max_length=20),
        ),
        migrations.AddIndex(
            model_name='notificationevent',
            index=models.Index(fields=['workflow_status', 'priority'], name='notificatio_workflo_44dbc5_idx'),
        ),
    ]
