# Generated by Django 4.2.7 on 2026-05-14 04:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        ('hrms', '0002_shift_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generated', 'Generated'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('posted', 'Posted')], default='draft', max_length=20)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_runs', to='accounting.journalentry')),
                ('period', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_run', to='hrms.payrollperiod')),
            ],
            options={
                'ordering': ['-period__start_date', '-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='PayrollLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('base_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payable_days', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('present_days', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('leave_days', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('absent_days', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('gross_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_lines', to='hrms.employee')),
                ('payroll_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='hrms.payrollrun')),
            ],
            options={
                'ordering': ['employee__department', 'employee__last_name', 'employee__first_name'],
            },
        ),
        migrations.AddConstraint(
            model_name='payrollline',
            constraint=models.UniqueConstraint(fields=('payroll_run', 'employee'), name='unique_employee_payroll_line'),
        ),
    ]
