# Generated by Django 4.2.7 on 2026-05-14 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0004_payrollline_allowances_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollrun',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_runs', to='hrms.payrollperiod'),
        ),
        migrations.AlterField(
            model_name='payrollrun',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('posted', 'Posted'), ('paid', 'Paid'), ('canceled', 'Canceled')], default='draft', max_length=20),
        ),
    ]
