# Generated by Django 4.2.7 on 2026-05-24 01:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_fiscalperiod_journalentry_fiscal_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('tax_type', models.CharField(choices=[('sales', 'Sales'), ('purchase', 'Purchase'), ('both', 'Sales and Purchase')], default='sales', max_length=20)),
                ('rate', models.DecimalField(decimal_places=3, max_digits=7)),
                ('description', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tax_rates', to='accounting.account')),
            ],
            options={
                'ordering': ['tax_type', 'name'],
            },
        ),
    ]
