# Generated by Django 4.2.7 on 2026-05-24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0004_vendorbill_vendorbillline'),
    ]

    operations = [
        migrations.CreateModel(
            name='NightAuditSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('enabled', models.BooleanField(default=False)),
                ('run_time', models.TimeField(default=datetime.time(2, 0))),
                ('timezone', models.CharField(default='Asia/Katmandu', max_length=80)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NightAuditRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('audit_date', models.DateField()),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('completed_with_exceptions', 'Completed with Exceptions'), ('failed', 'Failed')], default='completed', max_length=40)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('checked_in_bookings', models.PositiveIntegerField(default=0)),
                ('folios_reviewed', models.PositiveIntegerField(default=0)),
                ('room_charge_lines_created', models.PositiveIntegerField(default=0)),
                ('open_folios', models.PositiveIntegerField(default=0)),
                ('paid_folios', models.PositiveIntegerField(default=0)),
                ('exceptions', models.JSONField(blank=True, default=list)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='night_audit_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-audit_date', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='nightauditrun',
            constraint=models.UniqueConstraint(fields=('audit_date',), name='unique_night_audit_run_date'),
        ),
    ]
