# Generated by Django 4.2.7 on 2026-05-23 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0012_guestfollowupreminder_and_more'),
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otachannel',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='otachannel',
            name='schema_name',
        ),
        migrations.AddField(
            model_name='otachannel',
            name='provider',
            field=models.CharField(choices=[('zodomus', 'Zodomus'), ('booking_com', 'Booking.com'), ('expedia', 'Expedia'), ('airbnb', 'Airbnb'), ('manual', 'Manual / Generic')], default='manual', max_length=40),
        ),
        migrations.AddField(
            model_name='otachannel',
            name='settings',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='otachannel',
            name='sync_direction',
            field=models.CharField(choices=[('push', 'Push'), ('pull', 'Pull'), ('both', 'Push and Pull')], default='both', max_length=10),
        ),
        migrations.AlterField(
            model_name='otachannel',
            name='api_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='otachannel',
            name='api_secret',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='otachannel',
            name='base_url',
            field=models.URLField(blank=True),
        ),
        migrations.CreateModel(
            name='OTASyncJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(choices=[('availability_push', 'Availability Push'), ('rate_push', 'Rate Push'), ('booking_pull', 'Booking Pull'), ('webhook', 'Webhook')], max_length=40)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_jobs', to='integrations.otachannel')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OTAChannelRoomTypeMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_room_type_id', models.CharField(max_length=120)),
                ('external_room_type_name', models.CharField(blank=True, max_length=160)),
                ('is_active', models.BooleanField(default=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_type_mappings', to='integrations.otachannel')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ota_mappings', to='bookings.roomtype')),
            ],
            options={
                'ordering': ['channel__name', 'room_type__name'],
            },
        ),
        migrations.CreateModel(
            name='OTAChannelRatePlanMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_rate_plan_id', models.CharField(max_length=120)),
                ('external_rate_plan_name', models.CharField(blank=True, max_length=160)),
                ('is_active', models.BooleanField(default=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_plan_mappings', to='integrations.otachannel')),
                ('rate_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ota_mappings', to='bookings.rateplan')),
            ],
            options={
                'ordering': ['channel__name', 'rate_plan__name'],
            },
        ),
        migrations.CreateModel(
            name='OTAWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_event_id', models.CharField(max_length=160)),
                ('event_type', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('duplicate', 'Duplicate'), ('failed', 'Failed')], default='received', max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_events', to='integrations.otachannel')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['channel', 'status'], name='integration_channel_e0d974_idx'), models.Index(fields=['event_type'], name='integration_event_t_d92868_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='otawebhookevent',
            constraint=models.UniqueConstraint(fields=('channel', 'external_event_id'), name='unique_ota_webhook_event'),
        ),
        migrations.AddIndex(
            model_name='otasyncjob',
            index=models.Index(fields=['channel', 'sync_type', 'status'], name='integration_channel_d5e193_idx'),
        ),
        migrations.AddIndex(
            model_name='otasyncjob',
            index=models.Index(fields=['created_at'], name='integration_created_442bb5_idx'),
        ),
        migrations.AddConstraint(
            model_name='otachannelroomtypemapping',
            constraint=models.UniqueConstraint(fields=('channel', 'room_type'), name='unique_ota_channel_room_type'),
        ),
        migrations.AddConstraint(
            model_name='otachannelroomtypemapping',
            constraint=models.UniqueConstraint(fields=('channel', 'external_room_type_id'), name='unique_ota_channel_external_room_type'),
        ),
        migrations.AddConstraint(
            model_name='otachannelrateplanmapping',
            constraint=models.UniqueConstraint(fields=('channel', 'rate_plan'), name='unique_ota_channel_rate_plan'),
        ),
        migrations.AddConstraint(
            model_name='otachannelrateplanmapping',
            constraint=models.UniqueConstraint(fields=('channel', 'external_rate_plan_id'), name='unique_ota_channel_external_rate_plan'),
        ),
    ]
