# Generated by Django 4.2.7 on 2026-05-23 03:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0012_guestfollowupreminder_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('integrations', '0002_alter_otachannel_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTAReservationImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_reservation_id', models.CharField(max_length=160)),
                ('external_room_type_id', models.CharField(blank=True, max_length=120)),
                ('external_rate_plan_id', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('conflict', 'Conflict'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('canceled', 'Canceled')], default='pending', max_length=20)),
                ('conflict_type', models.CharField(choices=[('none', 'None'), ('duplicate', 'Duplicate'), ('missing_mapping', 'Missing Mapping'), ('no_room_available', 'No Room Available'), ('invalid_dates', 'Invalid Dates'), ('guest_blacklisted', 'Guest Blacklisted')], default='none', max_length=40)),
                ('conflict_message', models.TextField(blank=True)),
                ('guest_first_name', models.CharField(blank=True, max_length=120)),
                ('guest_last_name', models.CharField(blank=True, max_length=120)),
                ('guest_email', models.EmailField(blank=True, max_length=254)),
                ('guest_phone', models.CharField(blank=True, max_length=40)),
                ('check_in_date', models.DateField(blank=True, null=True)),
                ('check_out_date', models.DateField(blank=True, null=True)),
                ('number_of_guests', models.PositiveIntegerField(default=1)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(blank=True, max_length=3)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('normalized_payload', models.JSONField(blank=True, default=dict)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ota_imports', to='bookings.booking')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_imports', to='integrations.otachannel')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_ota_imports', to=settings.AUTH_USER_MODEL)),
                ('webhook_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation_imports', to='integrations.otawebhookevent')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['channel', 'status'], name='integration_channel_f8213d_idx'), models.Index(fields=['external_reservation_id'], name='integration_externa_20c733_idx'), models.Index(fields=['check_in_date', 'check_out_date'], name='integration_check_i_56a562_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='otareservationimport',
            constraint=models.UniqueConstraint(fields=('channel', 'external_reservation_id'), name='unique_ota_reservation_import'),
        ),
    ]
