# Generated by Django 4.2.7 on 2026-05-23 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_otareservationimport_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otareservationimport',
            name='conflict_type',
            field=models.CharField(choices=[('none', 'None'), ('duplicate', 'Duplicate'), ('missing_mapping', 'Missing Mapping'), ('no_room_available', 'No Room Available'), ('invalid_dates', 'Invalid Dates'), ('guest_blacklisted', 'Guest Blacklisted'), ('modification_review', 'Modification Review'), ('cancellation_review', 'Cancellation Review')], default='none', max_length=40),
        ),
    ]
