# Generated by Django 4.2.7 on 2026-05-09 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_kitchenticket_restaurantorder_restaurantorderline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantorder',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='restaurantorder',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurantorder',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('card', 'Card'), ('wallet', 'Wallet'), ('room_posting', 'Room Posting'), ('bank_transfer', 'Bank Transfer')], max_length=30),
        ),
        migrations.AlterField(
            model_name='restaurantorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent_to_kitchen', 'Sent To Kitchen'), ('preparing', 'Preparing'), ('served', 'Served'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='draft', max_length=30),
        ),
    ]
