# Generated by Django 4.2.7 on 2026-05-09 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_guestfolioline_and_more'),
        ('restaurant', '0003_restaurantorder_paid_amount_restaurantorder_paid_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantorder',
            name='room_booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='restaurant_orders', to='bookings.booking'),
        ),
    ]
