# Generated by Django 4.2.7 on 2026-05-12 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('restaurant', '0004_restaurantorder_room_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='inventory_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='menu_items', to='inventory.inventoryitem'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='inventory_quantity_per_unit',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
    ]
