# Generated by Django 4.2.7 on 2026-05-17 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurant', '0006_menuitem_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashierCounter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('outlet_type', models.CharField(choices=[('reception', 'Reception'), ('restaurant', 'Restaurant'), ('pool', 'Pool'), ('spa', 'Spa'), ('bar', 'Bar'), ('banquet', 'Banquet'), ('other', 'Other')], default='other', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['outlet_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CashierShift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('business_date', models.DateField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=20)),
                ('opening_cash', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('expected_cash', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('expected_card', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('expected_wallet', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('expected_bank_transfer', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('expected_room_posting', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('expected_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('actual_cash', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cash_variance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cashier_shifts', to=settings.AUTH_USER_MODEL)),
                ('counter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to='restaurant.cashiercounter')),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
    ]
