# Generated by Django 4.2.7 on 2026-05-18 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurant', '0008_restaurantorder_cashier_shift'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantOrderApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('action_type', models.CharField(choices=[('void_line', 'Void Item'), ('discount', 'Discount'), ('complimentary', 'Complimentary Bill')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('reason', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_notes', models.TextField(blank=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurant_approval_decisions', to=settings.AUTH_USER_MODEL)),
                ('line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_requests', to='restaurant.restaurantorderline')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='restaurant.restaurantorder')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurant_approval_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'action_type'], name='restaurant__status_c039b7_idx'), models.Index(fields=['order', 'status'], name='restaurant__order_i_119bae_idx')],
            },
        ),
    ]
