# Generated by Django 4.2.7 on 2026-05-18 11:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_restaurantorderapproval'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuModifierGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('selection_type', models.CharField(choices=[('single', 'Single'), ('multiple', 'Multiple')], default='single', max_length=20)),
                ('is_required', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('menu_items', models.ManyToManyField(blank=True, related_name='modifier_groups', to='restaurant.menuitem')),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MenuModifier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(max_length=50)),
                ('price_delta', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifiers', to='restaurant.menumodifiergroup')),
            ],
            options={
                'ordering': ['group__display_order', 'display_order', 'name'],
                'unique_together': {('group', 'code')},
            },
        ),
        migrations.AddField(
            model_name='restaurantorderline',
            name='modifiers',
            field=models.ManyToManyField(blank=True, related_name='order_lines', to='restaurant.menumodifier'),
        ),
    ]
