# Generated by Django 4.2.7 on 2026-05-18 14:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_purchaseorder_purchaseorderline'),
        ('restaurant', '0010_menumodifiergroup_menumodifier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuRecipeIngredient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipe_ingredients', to='inventory.inventoryitem')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingredients', to='restaurant.menuitem')),
            ],
            options={
                'ordering': ['item__name'],
                'unique_together': {('menu_item', 'item')},
            },
        ),
    ]
