# Generated by Codex on 2026-05-19

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0012_restaurantorderpayment_and_split_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantChargeConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('code', models.CharField(default='default', max_length=40, unique=True)),
                ('name', models.CharField(default='Default restaurant charges', max_length=120)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('service_charge_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('apply_tax', models.BooleanField(default=True)),
                ('apply_service_charge', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
