# Generated by Django 4.2.7 on 2026-05-20 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurant', '0013_restaurantchargeconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantorder',
            name='receipt_issued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurantorder',
            name='receipt_number',
            field=models.CharField(blank=True, db_index=True, max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='restaurantorder',
            name='receipt_reprint_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='RestaurantReceiptReprint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('receipt_number', models.CharField(max_length=40)),
                ('reprinted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('cashier_shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurant_receipt_reprints', to='restaurant.cashiershift')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_reprints', to='restaurant.restaurantorder')),
                ('reprinted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurant_receipt_reprints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reprinted_at'],
                'indexes': [models.Index(fields=['receipt_number'], name='restaurant__receipt_cc2908_idx'), models.Index(fields=['reprinted_at'], name='restaurant__reprint_af459a_idx')],
            },
        ),
    ]
