# Generated by Django 4.2.7 on 2026-05-22 06:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentIntent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('source_module', models.CharField(choices=[('guest_folio', 'Guest Folio'), ('restaurant_order', 'Restaurant Order'), ('purchase_order', 'Purchase Order'), ('manual', 'Manual')], db_index=True, max_length=40)),
                ('source_id', models.CharField(db_index=True, max_length=80)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='NPR', max_length=8)),
                ('provider', models.CharField(choices=[('manual', 'Manual'), ('mock', 'Mock'), ('khalti', 'Khalti'), ('esewa', 'eSewa'), ('stripe', 'Stripe')], db_index=True, default='manual', max_length=30)),
                ('provider_reference', models.CharField(blank=True, db_index=True, max_length=160)),
                ('idempotency_key', models.CharField(max_length=160, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('requires_action', 'Requires Action'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('canceled', 'Canceled')], db_index=True, default='draft', max_length=30)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('callback_payload', models.JSONField(blank=True, default=dict)),
                ('failure_message', models.TextField(blank=True)),
                ('succeeded_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payment_intents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['source_module', 'source_id'], name='payments_pa_source__f8f134_idx'), models.Index(fields=['provider', 'provider_reference'], name='payments_pa_provide_ea961b_idx'), models.Index(fields=['status', 'created_at'], name='payments_pa_status_79eeea_idx')],
            },
        ),
    ]
