# Generated by Django 4.2.7 on 2026-05-22 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentintent',
            name='provider_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
