# Generated by Django 4.2.7 on 2026-05-22 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_paymentintent_provider_payload'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentintent',
            name='settled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='settlement_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='settlement_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('settled', 'Settled'), ('skipped', 'Skipped'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20),
        ),
    ]
