# Generated by Django 4.2.7 on 2026-05-22 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0003_paymentintent_settled_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentintent',
            name='follow_up_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='follow_up_status',
            field=models.CharField(choices=[('none', 'None'), ('open', 'Open'), ('in_review', 'In Review'), ('resolved', 'Resolved')], db_index=True, default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_payment_intents', to=settings.AUTH_USER_MODEL),
        ),
    ]
