# Generated by Django 4.2.7 on 2026-05-08 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformuser',
            name='is_tenant_admin',
            field=models.BooleanField(default=False),
        ),
    ]
