# Generated by Django 4.2.7 on 2026-05-08 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('users', '0002_platformuser_is_tenant_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='permission',
            name='module',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='role',
            name='code',
            field=models.CharField(default='custom', max_length=128),
        ),
        migrations.AddField(
            model_name='role',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='tenants.tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('tenant', 'code')},
        ),
    ]
